index:
   path: /home/
   controller: App\Controller\MainController::index

presentation:
    path: /{nomdepage}/
    controller: App\Controller\MainController::pageName

page:
    path: /{nomdossierpage}/{nomdepage}/
    controller: App\Controller\MainController::pageFormulaireName

pdf:
    path: /pdf/
    controller: App\Controller\MainController::PdfController
